name: CI_DruzhenkoDiana_3-21

on:
  push:
    branches:
      - main
      - master
      - '**'

jobs:
  build:
    name: CMake build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run program
        run: ./build/tictactoe || echo "Execution skipped on GitHub runner"