name: CI_LastnameFirstname_Group

on:
  push:
    branches:
      - main
      - master
      - '**' 

jobs:
  build:
    name: CMake build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@v3

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run program
        run: ./build/OPI8
